### ISSUE TITLE
Adding Community Resource

### ISSUE THREAD

**Issue by Zoning2deep** [aorumbayev/awesome-algorand#114]
Hi,

Would it be possible for someone with the technical knowledge to add AlgoDaddy as a community resource to repository? The webpage is www.algodaddy.org and it offers over 30+ guides on the Algorand ecosystem for both beginners and intermediate users.

Also, thank you for the lovely website!

**Comment by aorumbayev** [comment]
Added under community projects section - thanks for proposal - closing issue
