### ISSUE TITLE
Duplicate in Blockchain Explorers

### ISSUE THREAD

**Issue by cusma** [aorumbayev/Awesome-Algorand#15]
https://github.com/aorumbayev/Awesome-Algorand/blob/71abf88c38844bc3545b396ab9d84cf919d3693a/README.md?plain=1#L79

This is a duplicate of [How Big is Algorand?](https://github.com/aorumbayev/Awesome-Algorand/blob/71abf88c38844bc3545b396ab9d84cf919d3693a/README.md?plain=1#L73)

**Comment by aorumbayev** [comment]
@cusma great catch! 

Fixed in this pr -> https://github.com/aorumbayev/Awesome-Algorand/pull/16
