### ISSUE TITLE
Categories overlap

### ISSUE THREAD

**Issue by cusma** [aorumbayev/Awesome-Algorand#27]
**Is your feature request related to a problem? Please describe.**
With the introduction of Metrics there is could be a conceptual overlap between [Blockchain Explorers](https://github.com/aorumbayev/Awesome-Algorand#blockchain-explorers) and [Metrics](https://github.com/aorumbayev/Awesome-Algorand#metrics) categories.

**Describe the solution you'd like**
Solving the ambiguity by moving the following items from Blockchain Explorer to Metrics:

- [How Big is Algorand?](https://github.com/aorumbayev/Awesome-Algorand/blame/main/README.md#L77)
- [Algorand Mempool](https://github.com/aorumbayev/Awesome-Algorand/blame/main/README.md#L80)
- [Metrika](https://github.com/aorumbayev/Awesome-Algorand/blame/main/README.md#L81)
- [Algorand Stats](https://github.com/aorumbayev/Awesome-Algorand/blame/main/README.md#L83)

**Comment by aorumbayev** [comment]
@cusma addressed in -> https://github.com/aorumbayev/Awesome-Algorand/pull/28 , closing issue
